name: C/C++ CI

on:
  push:
    branches: [ "front" ]
  pull_request:
    branches: [ "front" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make
    - name: make test
      run: make test
